### ISSUE TITLE
Null check for widget.dialKey.globalPaintBounds

### ISSUE THREAD

**Issue by lukasz-grabski** [darioielardi/flutter_speed_dial#242] opened 2022-04-18 18:33 UTC
Regarding this ticket: #198 

Fix works fine when using **SpeedDialDirection.up,** error is still there for **SpeedDialDirection.down:**

```
#0      _ChildrensOverlayState.build (package:flutter_speed_dial/src/speed_dial.dart:568:51)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4870:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4754:15)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#5      StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
```

**Comment by luca-colazzo** [comment] 2022-04-20 08:34
Duplicate of #198

**Closed by luca-colazzo** 2022-04-20 08:34 UTC
