### ISSUE TITLE
speed dial + bottom app bar = BOOM!

### ISSUE THREAD

**Issue by VadimOsovsky** [darioielardi/flutter_speed_dial#55] opened 2020-01-15 15:09 UTC
![IMG_47AF9C0B36EB-1](https://user-images.githubusercontent.com/39897981/72444997-1264cb00-37c2-11ea-8201-26ad89becd2c.jpeg)

```
BottomAppBar(shape: CircularNotchedRectangle())
```
```
floatingActionButtonLocation: FloatingActionButtonLocation.endDocked,
```

**Comment by marciocesarcorrea** [comment] 2020-01-19 21:02
The same thing happens to me

**Comment by marciocesarcorrea** [comment] 2020-01-19 21:02
The same thing happens to me

**Comment by JohnPinto** [comment] 2020-02-21 19:22
Same problem as well :cry:

**Comment by prateekmedia** [comment] 2021-01-31 15:56
Duplicate of #75 let's discuss this their

**Closed by prateekmedia** 2021-01-31 15:56 UTC
