### ISSUE TITLE
flutter_speed_dial Error: Required named parameter 'vsync' must be provided.

### ISSUE THREAD

**Issue by MSyarifH** [darioielardi/flutter_speed_dial#219] opened 2021-11-25 10:00 UTC
hi i am wanna trying use this plugin, but i encounter  error when pressing run project 

error log :

```
../../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_speed_dial-4.4.0/lib/src/animated_floating_button.dart:86:23: Error: Required named parameter 'vsync' must be provided.
        : AnimatedSize(
                      ^
../../../FlutterDev/flutter/packages/flutter/lib/src/widgets/animated_size.dart:56:9: Context: Found this candidate, but the arguments don't match.
  const AnimatedSize({
        ^^^^^^^^^^^^


FAILURE: Build failed with an exception.

```
version that i am working with :
`  flutter_speed_dial: ^4.4.0`

`Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale en-ID)`

**Comment by prateekmedia** [comment] 2021-11-25 10:01
Update your flutter SDK please, duplicate of #203

**Closed by prateekmedia** 2021-11-25 10:01 UTC

**Comment by MSyarifH** [comment] 2021-11-25 10:07
thank you
