### ISSUE TITLE
Flutter 2.5: Null check operator used on a null value - on toggleOverlay's dialkey globalPaintBounds

### ISSUE THREAD

**Issue by CP-casp** [darioielardi/flutter_speed_dial#198] opened 2021-09-15 10:25 UTC
![image](https://user-images.githubusercontent.com/89813054/133416974-254da859-e0bd-466c-9de0-c4282f2e0308.png)

```
The following _CastError was thrown building _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#2df95](dirty, state: _OverlayEntryWidgetState#daf4c):
Null check operator used on a null value
```

It appears to be thrown exactly on line 347 when `dialKey.globalPaintBounds` is being accessed but is null.

This is happening on second open. I can open and close but then not open again without this error.

**Comment by prateekmedia** [comment] 2021-09-15 10:37
This project currently doesn't have a active maintainer, if you have a solution then create a PR.

Also it seems like this error happens after hot reload only?

**Comment by CP-casp** [comment] 2021-09-15 22:20
It's not on hot-reload. But thanks for that, hopefully I can come up with a solution soon.

**Comment by CP-casp** [comment] 2021-09-20 01:31
Oh I think I should probably add that this is with Flutter 2.5. I'll add that to the title as well.

**Comment by prateekmedia** [comment] 2021-09-20 05:05
@CP-casp checked it with latest flutter beta and this issue is not coming to me.

**Comment by prateekmedia** [comment] 2021-09-20 05:06
Please check if you can reproduce this with the example project. I am not experiencing it.

**Comment by AlekseyMak** [comment] 2021-09-21 08:36
Got the same error. Trying to create minimal example

**Comment by CP-casp** [comment] 2021-09-21 21:17
@prateekmedia please remove the invalid flag

**Comment by rohirait** [comment] 2021-09-22 10:00
This issue starts at 4.1. Quickfix is to rollback to 3.0.5

**Comment by CP-casp** [comment] 2021-09-24 01:10
Only seeing this on Android, not iOS simulator.

**Comment by victorgvieira** [comment] 2021-09-24 03:33
Same issue here, i'm using the SpeedDial inside of an AlertDialog.
I noticed that this error happens when the dial group is open when the page/screen is popped
One, temporally, solution that i found was close the SpeedDial on SpeedDialChild tap and/or before the page is pop

// as widget field
ValueNotifier<bool> isDialOpen = ValueNotifier(false);

// when creating the SpeedDial
 Padding(
    // this will listen the back button and close the SpeedDial
     child: WillPopScope(
        onWillPop: () async {
             if (isDialOpen.value) {                
                isDialOpen.value = false;
                return false;
            }
             return true;
         },
            child: _createFabActions())
          ....................



// on SpeedDial
return SpeedDial(
     // listen the open/close event
      openCloseDial: isDialOpen,
      onClose: () => isDialOpen.value = false,
      onOpen: () => isDialOpen.value = true,
     .........

// on SpeedDialChild
SpeedDialChild(
          onTap: () async {
            // close the SpeedDial group
             isDialOpen.value = false;
            // Give some time to animation ends
             await new Future.delayed(const Duration(milliseconds: 100));
            // call the function
             myTapFunction();
        },
       .......

**Comment by victorgvieira** [comment] 2021-09-24 03:35
But i hope that this error could be fixed as soon as possible to avoid not handled situations :smile:

**Comment by prateekmedia** [comment] 2021-09-24 03:38
I think there is a problem while disposing the speed dial will have to check, thanks @victorgvieira for telling the problem and temporary solution

**Comment by CP-casp** [comment] 2021-09-30 02:04
Another interesting finding is that this error is not reproducable on 64bit emulators. And not on any iOS emulators or physical devices.

**Comment by samatzhusup** [comment] 2022-02-04 12:14
@prateekmedia Hi!

i showing error null check(
flutter_speed_dial: ^5.0.0+1
 
.globalPaintBounds!

**Comment by luca-colazzo** [comment] 2022-04-02 15:30
Try with the latest version: 5.1.0

**Comment by lukasz-grabski** [comment] 2022-04-18 16:45
This issue happens also to me, flutter_speed_dial version 5.1.0 :/

**Comment by lukasz-grabski** [comment] 2022-04-18 18:22
Here is the stack trace:

```
The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///opt/projects/portier/mobile/lib/main.dart:20:12
When the exception was thrown, this was the stack: 
#0      _ChildrensOverlayState.build (package:flutter_speed_dial/src/speed_dial.dart:568:51)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4870:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4754:15)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#5      StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
```

I'm using SpeedDial inside FutureBuilder, when pressing one of the buttons in the dial I re-fetch data with new Feature object. This error appears because animation of closing the menu has not beeen finished while changing Future value.

**Comment by lukasz-grabski** [comment] 2022-04-18 18:30
I know what is the problem, it has been fixed only for SpeedDialDirection.down, error is still valid for SpeedDialDirection.up

**Comment by lukasz-grabski** [comment] 2022-04-19 07:52
> I know what is the problem, it has been fixed only for SpeedDialDirection.down, error is still valid for SpeedDialDirection.up

Sorry, I was tired yesterday ;) I ment the opposite, works fine for direction.up but not for direction.down

**Comment by lukasz-grabski** [comment] 2022-04-25 11:39
@darshanpp would u have some spare time to handle it? ;)

**Comment by lukasz-grabski** [comment] 2022-04-30 10:29
Ok, just checked it on latest github version and it seems everything works pretty well :) I think this can be closed.

**Comment by luca-colazzo** [comment] 2022-04-30 10:51
Perfect,
Note that the latest github version has already been released on pub.dev as version 6.0.0

**Closed by luca-colazzo** 2022-04-30 10:51 UTC

**Comment by prateekmedia** [comment] 2022-06-16 02:09
@calvin-verticalscope Please create a PR for that, I am here to merge.

**Comment by calvin-verticalscope** [comment] 2022-06-16 02:14
> @calvin-verticalscope Please create a PR for that, I am here to merge.

I can do that first thing tomorrow morning

**Comment by calvin-verticalscope** [comment] 2022-06-16 13:47
I opened a PR https://github.com/darioielardi/flutter_speed_dial/pull/260. The PR also included some refactor on the file because my set up auto fixes things on file save, and I figure it doesn't hurt. If you want the refactors removed let me know, I can create a different PR.

**Comment by luca-colazzo** [comment] 2022-06-16 15:18
Mrged
